//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Actor
    {
        [Required]
        [Display(Name = "Actor_ID")]
        public int iActor_ID { get; set; }

        [Required]
        [Display(Name = "Nombre del actor")]
        public string vFirstName { get; set; }

        [Required]
        [Display(Name = "Apellido del actor")]
        public string vLastName { get; set; }
    }
}
