//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Payments = new HashSet<Payment>();
            this.Rentals = new HashSet<Rental>();
        }
    
        [Required]
        [Display(Name="Customer_ID")]
        public int iCustomer_ID { get; set; }

        [Required]
        [Display(Name = "Store_ID")]
        public Nullable<int> iStore_ID { get; set; }

        [Required]
        [Display(Name = "Nombre del cliente")]
        public string vFirstName { get; set; }

        [Required]
        [Display(Name = "Apellido del cliente")]
        public string vLastName { get; set; }

        [Required]
        [Display(Name = "Correo del cliente")]
        public string vEMail { get; set; }

        [Required]
        [Display(Name = "Direccion")]
        public Nullable<int> iAddress_ID { get; set; }

        [Required]
        [Display(Name = "Fecha de registro")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime iCreation_Date { get; set; }

        [Required]
        [Display(Name = "Activo")]
        public Nullable<byte> tActive_ID { get; set; }
    
        public virtual Active Active { get; set; }
        public virtual Address Address { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
