//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Rentals = new HashSet<Rental>();
        }

        [Required]
        [Display(Name = "Inventario_ID")]
        public int iInventory_ID { get; set; }

        [Required]
        [Display(Name = "Pelicula_ID")]
        public Nullable<int> iFilm_ID { get; set; }

        [Required]
        [Display(Name = "Tienda_ID")]
        public Nullable<int> iStore_ID { get; set; }

        [Required]
        [Display(Name = "Stock")]
        [Range(0, 500, ErrorMessage = "Valor inválido")]

        public short sQuantity { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
