//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        public int iPayment_ID { get; set; }
        [Display(Name = "Cliente_ID")]
        public Nullable<int> iCustomer_ID { get; set; }

        [Display(Name = "Empleado_ID")]
        public Nullable<int> iStaff_ID { get; set; }
        public int iAmount { get; set; }
        public System.DateTime dPayment_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
