//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Rental
    {
        [Required]
        [Display(Name = "Renta_ID")]
        public int iRental_ID { get; set; }

        [Required]
        [Display(Name = "Fecha de registro")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime dRental_Date { get; set; }

        [Required]
        [Display(Name = "Inventario_ID")]
        public Nullable<int> iInventory_ID { get; set; }

        [Required]
        [Display(Name = "Cliente_ID")]
        public Nullable<int> iCustomer_ID { get; set; }

        [Required]
        [Display(Name = "Fecha de regreso")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime dReturn_Date { get; set; }

        [Required]
        [Display(Name = "Empleado_ID")]
        public Nullable<int> iStaff_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
