//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA_PRUEBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Payments = new HashSet<Payment>();
            this.Rentals = new HashSet<Rental>();
        }

        [Required]
        [Display(Name = "Empleado_ID")]
        public int iStaff_ID { get; set; }

        [Required]
        [Display(Name = "Nombre del empleado")]
        public string vFirstName { get; set; }

        [Required]
        [Display(Name = "Apellido del empleado")]
        public string vLastName { get; set; }

        [Required]
        [Display(Name = "Correo del empleado")]
        public string vEMail { get; set; }

        [Required]
        [Display(Name = "Direccion")]
        public Nullable<int> iAddress_ID { get; set; }

        [Required]
        [Display(Name = "Tienda_ID")]
        public Nullable<int> iStore_ID { get; set; }

        [Required]
        [Display(Name = "Activo")]
        public Nullable<byte> tActive_ID { get; set; }

        [Required]
        [Display(Name = "Usuario")]
        public string vUsername { get; set; }

        [Required]
        [Display(Name = "Contraseña")]
        public string vPassword { get; set; }
    
        public virtual Active Active { get; set; }
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual Store Store { get; set; }
    }
}
